### ISSUE TITLE
make it possible to add states or levels to projects

### ISSUE THREAD

**Issue by timomayer** [janrembold/staffing#8]
for example: "waiting for PM response", "requested an external developer"

**Comment by janrembold** [comment]
The project table already has a project status field that is currently only informative. 
Currently we have:
- Ordered
- Blocker
- On Hold

I think it would be good to extend this status with:
- Waiting for (PM) response
- Searching for Ressources
- Active Development

As a next step I would like to refactor the project view completely. I think about a filter (selectbox) that filters projects by its value. So can choose to see, for example, "All projects", "Not active", "Under active development", "Waiting for response" and so on...

@timomayer What do you think?

**Comment by janrembold** [comment]
Following status/levels are now (v0.5.0+) available for projects:
![screenshot 2018-10-20 09 06 14](https://user-images.githubusercontent.com/4015313/47252594-6bbb3e80-d447-11e8-96ef-358db3335501.png)
